blogapp/urls.py
from django.urls import path
from . import views

app_name = 'blogapp'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blogapp_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolioapp import views
from django.views.static import serve



urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blogapp.urls')),

    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class BlogModel(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateTimeField(default=timezone.now)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='blogapp/images/', blank=True)
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

portfolioapp/models.py
from django.db import models
from django.utils import timezone


# Create your models here.

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolioapp/images/')
    url = models.URLField(blank=True)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

blogapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import BlogModel

# Create your views here.
def all_blogs(request):
    blogs = BlogModel.objects.order_by('-date')
    return render(request, 'blogapp/all_blogs.html', {'blogs':blogs})

def detail(request, blogapp_id):
    blog = get_object_or_404(BlogModel, pk=blogapp_id)
    return render(request, 'blogapp/detail.html', {'blog':blog})

    

portfolioapp/views.py
from django.shortcuts import render
from .models import Project
# Create your views here.

def home(request):
    projects = Project.objects.all().order_by('-date')
    return render(request, 'portfolioapp/home.html', {'projects':projects})

blogapp/templates/blogapp/all_blogs.html
{% extends 'portfolioapp/base.html' %}
{% load static %}

{% block content %}

<div class="secondback">
    <div class="container">
      <br>
      <h1 class="heading06" data-en="Love you">Blog</h1>
  
      <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for blog in blogs %}
        <div class="col">
          <div class="card">
            {% if blog.image%}
            <img src="{{ blog.image.url }}" class="card-img-top"/>
            {% endif %}
            <div class="card-body">
                <a href="{% url 'blogapp:detail' blog.id %}"><h5 class="card-title">{{ blog.title }}</h5></a>
              <p class="card-text">
                {{ blog.description|truncatechars:30 }}
              </p>
            </div>
          </div>
        </div>
        {% endfor %}
        </div>
        <br>
        <div style="text-align: center;">Shuhei has written {{ blogs.count }} blog{{ blogs.count|pluralize }} whereas Prerana wrote "ZERO!!!"</div>

      </div><!-- /.container -->
  </div>


{% endblock %}

blogapp/templates/blogapp/detail.html
{% extends 'portfolioapp/base.html' %}

{% block content %}

<h1>{{ blog.title }}</h1>
<h2>--{{ blog.date|date:'F jS Y'}}--</h2>

{{ blog.description|safe }}

{% endblock %}

portfolioapp/templates/portfolioapp/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="icon" type='jpeg/css' href="{% static 'portfolioapp/us.png' %}">
    <title>Kuma/Prechan's Website</title>

    <style>
    .navbar {
    background: #efc28b;
    background-image: radial-gradient(#e2e6eb 20%, transparent 0),
    radial-gradient(#1981f7 20%, transparent 0);
    background-position: 0 0, 10px 10px;
    background-size: 20px 20px;
    }

    .secondback {
  background-color: #c3c8cd;
}

#top-img {
    height: 300px;
}

#title {
    color: rgb(244, 166, 114);
    text-shadow: 1px 1px 0px #7777aa, 2px 2px 0px #7777aa, 3px 3px 0px #7777aa, 4px 4px 0px #7777aa, 5px 5px 0px #7777aa;
}

.heading06 {
	position: relative;
	padding-top: 40px;
	font-size: 40px;
	text-align: center;
  color: rgb(58, 37, 23);
}

.heading06 span {
	position: relative;
	z-index: 2;
}

.heading06::before {
	content: attr(data-en);
	position: absolute;
	top: -20px;
	left: 50%;
	transform: translateX(-50%);
	color: rgba(224,66,114,0.2);
	font-size: 80px;
	font-style: italic;
}




    </style>
  </head>
  <body>

    <nav class="navbar navbar-light">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img src="{% static 'portfolioapp/pass.png' %}" alt="" width="50" height="50">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blogapp:all_blogs' %}">Blog</a>
            </li>
        </div>
      </div>
    </nav>
    


    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

portfolioapp/templates/portfolioapp/home.html
{% extends 'portfolioapp/base.html' %}

{% block content %}
{% load static %}

<style>
.masthead {
  height: 80vh;
  min-height: 300px;
  max-height: 600px;
  background-image: url({% static 'portfolioapp/moon.jpeg' %});
  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;
}

.secondback {
  background-color: #c3c8cd;
}

#top-img {
    height: 300px;
}

#title {
    color: rgb(244, 166, 114);
    text-shadow: 1px 1px 0px #7777aa, 2px 2px 0px #7777aa, 3px 3px 0px #7777aa, 4px 4px 0px #7777aa, 5px 5px 0px #7777aa;
}

.heading06 {
	position: relative;
	padding-top: 40px;
	font-size: 40px;
	text-align: center;
  color: rgb(58, 37, 23);
}

.heading06 span {
	position: relative;
	z-index: 2;
}

.heading06::before {
	content: attr(data-en);
	position: absolute;
	top: -20px;
	left: 50%;
	transform: translateX(-50%);
	color: rgba(224,66,114,0.2);
	font-size: 80px;
	font-style: italic;
}

.extra{
  text-align: center;
  padding-bottom: 30px;
}


</style>

<header class="masthead">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-12 text-center">
          <h1 class="fw-light" id="title">Kuma/Prechan's Website</h1>
          
          <img src="{% static 'portfolioapp/us.png' %}" class="img-fluid" id="top-img">
          <br>
          <br>
          <p style="color: #ffffff;" class="lead">This website is exclusively for lovely couples like us...</p>
          <a class="btn btn-danger btn-lg" href="https://www.youtube.com/@Gaai_san" role="button">Youtube</a>
        </div>
      </div>
    </div>
</header>


<div class="secondback">
  <div class="container">
    <br>
    <h1 class="heading06" data-en="Love you">Milestones</h1>

    <div class="row row-cols-1 row-cols-md-3 g-4">
      {% for project in projects %}
      <div class="col">
        <div class="card">
          <img src="{{ project.image.url }}" class="card-img-top"/>
          <div class="card-body">
            <h5 class="card-title">{{ project.title }}</h5>
            <p class="card-text">
              {{ project.description }}
            </p>
          </div>
        </div>
      </div>
      {% endfor %}
      </div>
    </div><!-- /.container -->
</div>

<br>
<div class="extra">
<a href="{% static 'portfolioapp/ourpics.pdf' %}" class="btn btn-warning">Our cute album</a>

<a href="{% url 'blogapp:all_blogs' %}" class="btn btn-primary">Blog list</a>
</div>




{% if project.url %}
    <a href="{{ project.url }}">Link</a>
{% endif %}


{% endblock %}